#!/usr/bin/python

def fib(x):
        if x == 1 or x == 2:
                return 1
        else:
                return fib(x-1) + fib(x-2)



for i in range(1,10):
        print fib(i)



#############################################

./fib.py 
1
1
2
3
5
8
13
21
34


